apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: newberdi/do9:session-service
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: POSTGRES_DB
          value: "users_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
      - name: hotel-service
        image: newberdi/do9:hotel-service
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: POSTGRES_DB
          value: "hotels_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-service
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
    spec:
      containers:
      - name: loyalty-service
        image: newberdi/do9:loyalty-service
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: POSTGRES_DB
          value: "balances_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: newberdi/do9:payment-service
        ports:
        - containerPort: 8084
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: POSTGRES_DB
          value: "payments_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: newberdi/do9:report-service
        ports:
        - containerPort: 8086
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: POSTGRES_DB
          value: "statistics_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: newberdi/do9:booking-service
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: POSTGRES_DB
          value: "reservations_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: newberdi/do9:gateway-service
        ports:
        - containerPort: 8087
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets