apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: devops-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
        version: v3
    spec:
      containers:
      - name: gateway-service
        image: newberdi/do9:gateway-service
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: APP_VERSION
          value: "v3-rolling"